export enum EventFiltersEnum {
    ALL = 'ALL',
    OTHER = 'OTHER',
    EXHIBITIONS = 'EXHIBITIONS',
    TRAINING = 'TRAINING',
    REGATTAS = 'REGATTAS',
    FLOTILLAS = 'FLOTILLAS',
    PRESENTATIONS = 'PRESENTATIONS',
    CONFERENCES = 'CONFERENCES',
    FORUMS = 'FORUMS',
}
