export const UNKNOWN_ERROR = 'UNKNOWN';
export const WRONG_SUBJECT_ERROR = 'WRONG_SUBJECT';
export const WRONG_PASSWORD_ERROR = 'WRONG_PASSWORD';
export const WRONG_CREDENTIALS_ERROR = 'WRONG_CREDENTIALS_ERROR';

export const USERNAME_TAKEN = 'USERNAME_TAKEN';
export const EMAIL_TAKEN = 'EMAIL_TAKEN';
