export enum NotSettingEnum {
    EVENT_TYPE = 'EVENT_TYPE',
    AUTHORED_POST_COMMENT = 'AUTHORED_POST_COMMENT',
    NOTIFY_REPORT = 'NOTIFY_REPORT',
    BOOKMARKED_POST_COMMENT = 'BOOKMARKED_POST_COMMENT',

    REPLY = 'REPLY',
    WATCHED_COMMENT_REPLY = 'WATCHED_COMMENT_REPLY',
    COMMENT_MENTION = 'COMMENT_MENTION',

    NOTIFY_SUBMITTED = 'NOTIFY_SUBMITTED',
    NOTIFY_PUBLISHED = 'NOTIFY_PUBLISHED',
    NOTIFY_BLOCKED = 'NOTIFY_BLOCKED',
    NOTIFY_REVIEWING = 'NOTIFY_REVIEWING',
    NOTIFY_DRAFTED = 'NOTIFY_DRAFTED',
}
