export const ROLES = {
    USER: 'ROLE_USER',
    SALES: 'ROLE_SALES',
    CHIEF_EDITOR: 'ROLE_CHIEF_EDITOR',
    SUPERUSER: 'ROLE_SUPERUSER',

    EDITOR$: ['ROLE_CHIEF_EDITOR', 'ROLE_SUPERUSER'],
    PRIV_USER$: ['ROLE_PRIVILEGED_USER', 'ROLE_CHIEF_EDITOR', 'ROLE_SUPERUSER']
};
