export enum BannerPlaceEnum {
    HEADER = 'HEADER',
    FEED1 = 'FEED1',
    FEED2 = 'FEED2',
    FEED3 = 'FEED3',
    PUBLICATION_ABOVE_COMMENTS = 'PUBLICATION_ABOVE_COMMENTS',
    PUBLICATION_BELOW_COMMENTS = 'PUBLICATION_BELOW_COMMENTS',
    PUBLICATION_SIDEBAR = 'PUBLICATION_SIDEBAR',
}
